apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_HOST: YXdzLXJkcy5jZDBhNmdxZ3UwcWMuZXUtbm9ydGgtMS5yZHMuYW1hem9uYXdzLmNvbQ==
  DB_USER: YWRtaW4=
  DB_PASS: cGFzc3dvcmQxMjM=
  DB_NAME: YXdzLXJkcw==
